apiVersion: v1
kind: Service
metadata:
  labels:
    app: daydown
  name: daydown
spec:
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: rpc
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: daydown
  sessionAffinity: None
  type: ClusterIP
